'use client'
import Head from "next/head";
import { createComponent } from "@lit/react";
import React from "react";
// import {TapsiButton} from '@tapsioss/web-components/button';
import {TapsiBottomSheet} from '@tapsioss/web-components/bottom-sheet';
import '@tapsioss/theme';

// const Button = createComponent({
//     react: React,
//     elementClass: TapsiButton,
//     tagName: "tapsi-button",
// });

const BottomSheet = createComponent({
    react: React,
    elementClass: TapsiBottomSheet,
    tagName: "tapsi-bottom-sheet",
});

export default function Home() {
    // const [open, setOpen] = React.useState(false)

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <main>
                    {/*<Button variant="brand" onClick={() => setOpen(!open)}>تست</Button>*/}
                    <BottomSheet headingTitle="تست" headingDescription="متنننن" open expandable>
                        من را باز کنید
                    </BottomSheet>
                </main>
            </div>
        </>
    );
}
